version: '3.8'

services:
  mqtt-broker:
    build: .
    ports:
      - "1883:1883"  # MQTT TCP
      - "8883:8883"  # MQTT WebSocket
      - "3000:3000"  # Web Monitor
    environment:
      - MQTT_PORT=1883
      - WS_PORT=8883
    restart: unless-stopped
    container_name: mqtt-broker
